name: sync-dust

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */2 * * *'
  repository_dispatch:
    types: sync-dust

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        git config --global user.name 'GitHub Actions' 
        git config --global user.email 'noreply@github.com'
    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone Master
      run: |
        git clone -b dust git@github.com:monk-coder/dust.git dust
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        directory: dust
        github_token: ${{ secrets.PAT }}
        branch: dust
        repository: "gossh520/sync"
