name: sync-jd_shell

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */2 * * *'

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        git config --global user.name 'GitHub Actions' 
        git config --global user.email 'noreply@github.com'
    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.SSH_JD }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone Master
      run: |
        git clone -b master git@gitee.com:evine/jd_shell.git jd_shell
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        directory: jd_shell
        github_token: ${{ secrets.PAT }}
        branch: jd_shell
